# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f147c790755b25a8a5045ac7f787ffc19ebc76defc081de89bb178017951a5eb486d11086ffe041ee708c5e8cbda82d5eea4890ff533c954e663aebd4d9dd3dc

test:
  secret_key_base: fd95437229a130c62d497b9eac3d4151ef0a5b0ce96e1bd68425b25c5b840809ab68c15b5af960202ae013d9eac67f24beba6a0ca33b95da2457f44371b77c87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
