# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76dd748027e180e373a89c157de3bf0b53a396866158b759e0fb440f010015f5e286361897f9f02ff32513d62f67109c26aca155fc84003e76019085f7b96457

test:
  secret_key_base: ab48b8ba60f9cd0a1a60c3d3a102c7ebe7f2cc69fb9562c2c63849df8394a62def2e999795f2ff890815c9458bdcf66246d2d46a817c5bafd523b47974994762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
