# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af7d4d6742a9bc0b54053bb1cfa13923b3ca1015a40f451367c58ebe308e5a5c3ace0f1ce9d03627a47e8c746623a85799afe4d76d88baa79af3ffa462eba842

test:
  secret_key_base: 13a409318b461cac7be47802c8b4dc2b62bc25a77e1c57d767f159f7b9919a6187d4a9ca26cd8eadfcaaaa0778abedd199112445f2984cdebc681569705ba874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
