# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8d04ad507bc216eede3dcbeb752e390c2300bd527dcf2c435ffb454df89a0dec6c302b0b5ff691dafed3bcb08b5529e8c63f08ecb5da95518b2b8b59f46a20

test:
  secret_key_base: 2ddfb8fc3d327119566a9c736bb406cff8fa35262dffe21ae95cd2950f9314ea270039bfaeb795a6ef173dbef10123c06e3a29e44417bdd934f3dc3330789342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
